const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const root = path.resolve(__dirname, "..");

test("homepage exposes the reference replica section structure", () => {
  const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
  const css = fs.readFileSync(path.join(root, "styles.css"), "utf8");
  const script = fs.readFileSync(path.join(root, "script.js"), "utf8");
  const particlesScript = fs.existsSync(path.join(root, "particles-bg.js"))
    ? fs.readFileSync(path.join(root, "particles-bg.js"), "utf8")
    : "";
  const orbitScript = fs.existsSync(path.join(root, "orbit-images.js"))
    ? fs.readFileSync(path.join(root, "orbit-images.js"), "utf8")
    : "";

  assert.match(html, /<link rel="stylesheet" href="styles\.css">/);
  assert.match(html, /gsap(?:\.min)?\.js/);
  assert.match(html, /ScrollTrigger(?:\.min)?\.js/);
  assert.match(html, /<script src="script\.js" defer><\/script>/);
  assert.doesNotMatch(html, /project-ascii-art\.js/);
  assert.match(html, /<script type="importmap">/);
  assert.match(html, /"three":\s*"https:\/\/cdn\.jsdelivr\.net\/npm\/three@0\.160\.1\/build\/three\.module\.js"/);
  assert.match(html, /"three\/addons\/":\s*"https:\/\/cdn\.jsdelivr\.net\/npm\/three@0\.160\.1\/examples\/jsm\/"/);
  assert.match(html, /<script type="module" src="hero-computer\.js\?v=hero-pause-offscreen-20260429b"><\/script>/);
  assert.doesNotMatch(html, /<script type="module" src="circular-gallery\.js"><\/script>/);
  assert.match(html, /<script type="module" src="particles-bg\.js"><\/script>/);
  assert.match(html, /<script type="module" src="orbit-images\.js"><\/script>/);
  assert.doesNotMatch(html, /<script type="module" src="text-sphere\.js"><\/script>/);
  assert.match(html, /Pixel trail disabled for performance/);
  assert.doesNotMatch(html, /<canvas class="pixel-trail-canvas"/);
  assert.doesNotMatch(html, /data-pixel-trail/);
  assert.match(html, /<div class="cursor-follower" data-cursor-follower aria-hidden="true"><\/div>/);
  assert.match(html, /<div class="hero-pin">\s*<section class="hero-page" id="intro" aria-label="Hero">/);
  assert.ok(
    html.indexOf('<section class="hero-page" id="intro"') < html.indexOf('<section class="manifesto" id="manifesto"'),
    "manifesto should sit directly after the hero in the document flow"
  );
  assert.ok(
    html.indexOf('<section class="manifesto" id="manifesto"') < html.indexOf('<section class="selected-projects" id="principles"'),
    "principles section should follow the manifesto"
  );
  assert.ok(
    html.indexOf('<section class="selected-projects" id="principles"') < html.indexOf('<section class="brag-zone" id="direction"'),
    "principles section should sit before direction"
  );
  assert.match(html, /<section class="brag-zone" id="direction" aria-labelledby="direction-title">/);
  assert.doesNotMatch(html, /class="direction-pin"/);
  assert.ok(
    html.indexOf('<section class="brag-zone" id="direction"') < html.indexOf('<section class="about-section project-spiral-section" id="projects"'),
    "direction section should sit before current projects"
  );
  assert.match(html, /<a href="#intro">介绍<\/a>/);
  assert.match(html, /<a href="#direction">方向<\/a>/);
  assert.match(html, /<a href="#principles">原则<\/a>/);
  assert.match(html, /<a href="#projects">项目<\/a>/);
  assert.match(html, /<a href="#contact">联系<\/a>/);
  assert.doesNotMatch(html, /<a href="#work">作品<\/a>/);
  assert.doesNotMatch(html, /<a href="#about">信息<\/a>/);
  assert.doesNotMatch(html, /signal-bar/);
  assert.doesNotMatch(html, /brand-lockup/);
  assert.match(html, /class="hero-portrait tilted-card-figure"/);
  assert.match(html, /hidden\s+data-portrait-hidden/);
  assert.match(html, /data-tilted-card/);
  assert.match(html, /data-rotate-amplitude="12"/);
  assert.match(html, /data-scale-on-hover="1\.08"/);
  assert.match(html, /class="tilted-card-inner"/);
  assert.match(html, /<img class="tilted-card-img" src="assets\/hero-portrait\.jpg" alt="Personal portrait">/);
  assert.match(html, /<figcaption class="tilted-card-caption" aria-hidden="true">NingHuohuo<\/figcaption>/);
  assert.match(html, /class="hero-computer"/);
  assert.match(html, /data-hero-computer/);
  assert.match(html, /aria-label="3D retro computer"/);
  assert.match(html, /data-screen-video="https:\/\/res\.cloudinary\.com\/divynfoap\/video\/upload\/f_auto,q_auto\/v1777333574\/4%E6%9C%8828%E6%97%A5_1_awcdzs\.mp4"/);
  assert.doesNotMatch(html, /data-decay-card/);
  assert.doesNotMatch(html, /id="hero-portrait-decay-filter"/);
  assert.doesNotMatch(html, /data-decay-displacement/);
  assert.match(html, /class="hero-clock"/);
  assert.match(html, /data-clock/);
  assert.match(html, /class="hero-greeting"/);
  assert.match(html, /data-text-type="Hi，我是宁火火 😎；欢迎来到我的个人主页。"/);
  assert.doesNotMatch(html, /个人网站/);
  assert.match(html, /data-text-type-content>Hi，我是宁火火 😎<\/span>/);
  assert.doesNotMatch(html, /class="text-type__line"/);
  assert.match(html, /class="text-type__cursor"/);
  assert.match(html, /class="hero-intro-copy"/);
  assert.match(html, /class="hero-intro-text"/);
  assert.match(html, /class="hero-intro-text" lang="zh-CN">一个从传统互联网人转型过来/);
  assert.doesNotMatch(html, /A person who came from the traditional internet world/);
  assert.doesNotMatch(html, /I care more about how AI can truly be used to get\s+results\./);
  assert.doesNotMatch(html, /ordinary people can truly use AI to get/);
  assert.match(html, /不追逐每一个 AI 工具，更关心怎么真正把 AI 用出结果/);
  assert.doesNotMatch(html, /更关心普通人怎么真正把 AI 用出结果/);
  assert.match(html, /class="hero-name variable-proximity-demo"/);
  assert.match(html, /data-variable-proximity/);
  assert.match(html, /data-variable-label="NINGHUOHUO"/);
  assert.match(html, /data-from-font-variation-settings="'wght' 700, 'opsz' 8"/);
  assert.match(html, /data-to-font-variation-settings="'wght' 1000, 'opsz' 72"/);
  assert.match(html, /data-variable-radius="140"/);
  assert.match(html, /data-variable-falloff="linear"/);
  assert.doesNotMatch(html, /data-split-text/);
  assert.doesNotMatch(html, /data-fit-text/);
  assert.doesNotMatch(html, /data-fit-scale/);
  assert.match(html, />NINGHUOHUO</);
  assert.equal((html.match(/data-variable-label="NINGHUOHUO"/g) || []).length, 1);
  assert.match(html, /<section class="manifesto" id="manifesto" aria-label="Manifesto">/);
  assert.match(html, /data-scroll-reveal/);
  assert.match(html, /data-base-opacity="0\.1"/);
  assert.match(html, /data-base-rotation="9"/);
  assert.match(html, /data-blur-strength="7"/);
  assert.doesNotMatch(html, /data-scroll-scrub/);
  assert.match(html, /data-enable-blur="true"/);
  assert.match(html, /data-rotation-end="bottom bottom"/);
  assert.match(html, /data-word-animation-end="bottom bottom"/);
  assert.match(html, /class="manifesto-en"/);
  assert.match(html, /class="manifesto-zh" lang="zh-CN"/);
  assert.doesNotMatch(html, /Born in the 90s/i);
  assert.match(html, /Based in Zhejiang/);
  assert.doesNotMatch(html, /90后/);
  assert.match(html, /坐标浙江/);
  assert.match(html, /擅长白日梦/);
  assert.match(html, /good at daydreaming/);
  assert.match(html, /AI内容创作者/);
  assert.match(html, /<section class="energy-section" id="energy" aria-labelledby="energy-title">/);
  assert.match(html, /<h1 id="energy-title"><span aria-hidden="true">↘<\/span> 我的力量源泉<\/h1>/);
  assert.match(html, /<div class="energy-stage" aria-hidden="true">\s*<div class="energy-particles particles-container" data-energy-particles><\/div>\s*<div class="energy-orbit orbit-container" data-energy-orbit><\/div>\s*<\/div>/);
  assert.match(html, /<section class="brag-zone" id="direction" aria-labelledby="direction-title">/);
  assert.match(html, /<div class="direction-reveal-content">\s*<div class="direction-single" aria-label="AI focus directions">/);
  assert.match(html, /<h1 id="direction-title"><span aria-hidden="true">↘<\/span> 我关注的方向<\/h1>/);
  assert.match(html, /<div class="direction-single" aria-label="AI focus directions">/);
  assert.equal((html.match(/data-direction-collage-image/g) || []).length, 1);
  assert.match(html, /class="direction-feature"/);
  assert.match(html, /class="direction-copy"/);
  assert.match(html, /class="direction-topic-list"/);
  assert.equal((html.match(/class="direction-topic"/g) || []).length, 5);
  assert.match(html, /<h2><span>AI产品与增长<\/span><span lang="en">AI Product & Growth<\/span><\/h2>/);
  assert.match(html, /<h2><span>AI自动化工作流<\/span><span lang="en">AI Automation Workflows<\/span><\/h2>/);
  assert.match(html, /<h2><span>AI一人公司变现项目<\/span><span lang="en">AI Solo-Business Monetization<\/span><\/h2>/);
  assert.match(html, /<h2><span>AI 内容与个人品牌<\/span><span lang="en">AI Content & Personal Brand<\/span><\/h2>/);
  assert.match(html, /<h2><span>AI变现逆向拆解<\/span><span lang="en">AI Monetization Reverse Engineering<\/span><\/h2>/);
  assert.match(html, /assets\/direction\/ai-product-growth\.jpg/);
  assert.doesNotMatch(html, /assets\/direction\/ai-automation-workflow\.jpg/);
  assert.doesNotMatch(html, /assets\/direction\/ai-solo-business\.jpg/);
  assert.doesNotMatch(html, /assets\/direction\/ai-content-brand\.jpg/);
  assert.doesNotMatch(html, /assets\/direction\/ai-monetization-analysis\.jpg/);
  assert.doesNotMatch(html, /class="direction-hover-overlay"/);
  assert.doesNotMatch(html, /class="direction-marquee"/);
  assert.match(html, /研究 AI 产品怎么被用户真正使用、传播和增长。/);
  assert.match(html, /Study how AI products are truly used, shared, and grown by users\./);
  assert.match(html, /用 AI 和自动化工具，把重复工作变成可复用流程。/);
  assert.match(html, /Turn repetitive work into reusable workflows with AI and automation tools\./);
  assert.match(html, /探索一个人如何用 AI 做更轻、更小、更自由的生意。/);
  assert.match(html, /Explore how one person can build a lighter, smaller, freer business with AI\./);
  assert.match(html, /记录一个普通人如何用 AI 做内容、做账号、做个人 IP。/);
  assert.match(html, /Document how an ordinary person uses AI for content, accounts, and personal IP\./);
  assert.match(html, /不看宏大叙事，只研究真实的变现逻辑。/);
  assert.match(html, /Ignore grand narratives and study the real logic behind monetization\./);
  assert.doesNotMatch(html, /data-card-swap/);
  assert.doesNotMatch(html, /direction-card/);
  assert.doesNotMatch(html, /data-direction-cards/);
  assert.doesNotMatch(html, /data-direction-card/);
  assert.doesNotMatch(html, /data-text-sphere/);
  assert.doesNotMatch(html, /aria-label="Looping focus direction text flow"/);
  assert.doesNotMatch(html, /data-scroll-stack/);
  assert.doesNotMatch(html, /edge-marks/);
  assert.match(html, /Ethan Mollick/);
  assert.match(html, /Naval Ravikant/);
  assert.match(html, /Kevin Kelly/);
  assert.match(html, /Andrej Karpathy/);
  assert.match(html, /Dan Koe/);
  assert.match(html, /Reid Hoffman/);
  assert.match(html, /Ali Abdaal/);
  assert.match(html, /Code and media are permissionless leverage/);
  assert.match(html, /永远让 AI 上桌/);
  assert.doesNotMatch(html, /不要把 AI 当成偶尔使用的软件/);
  assert.doesNotMatch(html, /data-card-stack/);
  assert.doesNotMatch(html, /stack-card-rotate/);
  assert.match(html, /<section class="selected-projects" id="principles" aria-labelledby="brag-title">/);
  assert.match(html, /<h1 id="brag-title"><span aria-hidden="true">↘<\/span> 我相信的工作原则<\/h1>/);
  assert.doesNotMatch(html, /<h1 id="brag-title"><span aria-hidden="true">\\<\/span> Brag Zone<\/h1>/);
  const principlesHtml = html.slice(
    html.indexOf('<section class="selected-projects" id="principles"'),
    html.indexOf('<section class="brag-zone" id="direction"')
  );
  assert.match(principlesHtml, /class="principles-intro-copy"/);
  assert.match(principlesHtml, /我不迷信任何一个人。/);
  assert.match(principlesHtml, /但我会长期观察那些真正改变我思考方式的人。/);
  assert.match(principlesHtml, /他们有的是 AI 公司创始人，有的是研究者，有的是创作者，有的是一人公司实践者。/);
  assert.match(principlesHtml, /I do not put blind faith in any one person\./);
  assert.match(principlesHtml, /But I keep observing the people who genuinely change the way I think\./);
  assert.match(principlesHtml, /Some are AI company founders, some are researchers, some are creators, and some are solo-company practitioners\./);
  assert.doesNotMatch(principlesHtml, /principles-pixel-flower/);
  assert.match(principlesHtml, /class="principles-sticky"/);
  assert.match(principlesHtml, /class="principles-scroll-stage" data-principles-scroll-stage aria-label="People and principles scroll sequence"/);
  assert.equal((principlesHtml.match(/class="principles-slide/g) || []).length, 7);
  assert.equal((principlesHtml.match(/data-principles-slide/g) || []).length, 7);
  assert.equal((principlesHtml.match(/data-principles-progress/g) || []).length, 0);
  assert.doesNotMatch(principlesHtml, /data-principles-carousel/);
  assert.doesNotMatch(principlesHtml, /principles-progress/);
  assert.doesNotMatch(principlesHtml, /principles-slide is-active/);
  assert.match(principlesHtml, /class="principles-person">Ethan Mollick/);
  assert.match(principlesHtml, /class="principles-role">Wharton professor, AI and work researcher/);
  assert.match(principlesHtml, /class="principles-quote-en">Always invite AI to the table\. You should try inviting AI to help you in everything you do\./);
  assert.match(principlesHtml, /class="principles-quote-zh" lang="zh-CN">永远让 AI 上桌。你应该尝试让 AI 参与到你做的每一件事里。/);
  assert.match(principlesHtml, /class="principles-role">Founding executive editor of WIRED, technology thinker, author of "1,000 True Fans"/);
  assert.match(principlesHtml, /class="principles-quote-en">To be a successful creator, you don't need millions\. You need only thousands of true fans\./);
  assert.match(principlesHtml, /class="principles-role">Former OpenAI and Tesla AI leader, computer scientist, AI educator/);
  assert.match(principlesHtml, /class="principles-quote-en">Software 1\.0 is eating the world, and now AI \/ Software 2\.0 is eating software\./);
  assert.match(principlesHtml, /class="principles-role">Solo-business creator, personal-brand and creator-monetization blogger/);
  assert.match(principlesHtml, /class="principles-quote-en">Solve your own problems, write about them online, and attract people who are trying to solve the same problems\./);
  assert.match(principlesHtml, /class="principles-role">LinkedIn co-founder, investor, Silicon Valley entrepreneur/);
  assert.match(principlesHtml, /class="principles-quote-en">If you are not embarrassed by the first version of your product, you've launched too late\./);
  assert.match(principlesHtml, /class="principles-role">Doctor-turned video creator and productivity blogger/);
  assert.match(principlesHtml, /class="principles-quote-en">The most successful creators are not the ones who know the most, but the ones who share what they are learning\./);
  assert.doesNotMatch(principlesHtml, /principles-pinboard/);
  assert.doesNotMatch(principlesHtml, /principles-note/);
  assert.doesNotMatch(principlesHtml, /principles-pin/);
  assert.doesNotMatch(principlesHtml, /principles-polaroid/);
  assert.doesNotMatch(principlesHtml, /principles-macbook/);
  assert.doesNotMatch(principlesHtml, /data-principles-macbook/);
  assert.doesNotMatch(principlesHtml, /principles-macbook-screen/);
  assert.doesNotMatch(principlesHtml, /principles-macbook-camera/);
  assert.doesNotMatch(principlesHtml, /principles-macbook-base/);
  assert.doesNotMatch(principlesHtml, /class="principles-viewport"/);
  assert.equal((principlesHtml.match(/data-principles-decay-card/g) || []).length, 7);
  assert.doesNotMatch(principlesHtml, /data-principles-decay-displacement/);
  assert.match(principlesHtml, /<img src="assets\/principles\/ethan-mollick\.png" alt="Ethan Mollick portrait">/);
  assert.match(principlesHtml, /<img src="assets\/principles\/naval-ravikant\.png" alt="Naval Ravikant portrait">/);
  assert.match(principlesHtml, /<img src="assets\/principles\/kevin-kelly\.png" alt="Kevin Kelly portrait">/);
  assert.match(principlesHtml, /<img src="assets\/principles\/andrej-karpathy\.png" alt="Andrej Karpathy portrait">/);
  assert.equal((principlesHtml.match(/data-principles-stack-source/g) || []).length, 0);
  assert.equal((principlesHtml.match(/id="principles-decay-filter-/g) || []).length, 0);
  assert.equal((principlesHtml.match(/data-principles-tilted-card/g) || []).length, 0);
  assert.equal((principlesHtml.match(/principles-photo-placeholder/g) || []).length, 0);
  assert.equal((principlesHtml.match(/<img class="principles-photo card-image"/g) || []).length, 0);
  assert.equal((principlesHtml.match(/<image class="principles-decay-image"/g) || []).length, 0);
  assert.ok(fs.existsSync(path.join(root, "assets/principles/ethan-mollick.png")));
  assert.ok(fs.existsSync(path.join(root, "assets/principles/naval-ravikant.png")));
  assert.ok(fs.existsSync(path.join(root, "assets/principles/kevin-kelly.png")));
  assert.ok(fs.existsSync(path.join(root, "assets/principles/andrej-karpathy.png")));
  assert.ok(fs.existsSync(path.join(root, "assets/principles/dan-koe.png")));
  assert.ok(fs.existsSync(path.join(root, "assets/principles/reid-hoffman.png")));
  assert.ok(fs.existsSync(path.join(root, "assets/principles/ali-abdaal.png")));
  assert.ok(fs.existsSync(path.join(root, "assets/principles/pixel-flower-transparent.png")));
  assert.ok(fs.existsSync(path.join(root, "assets/direction/ai-product-growth.jpg")));
  assert.ok(fs.existsSync(path.join(root, "assets/direction/ai-automation-workflow.jpg")));
  assert.ok(fs.existsSync(path.join(root, "assets/direction/ai-solo-business.jpg")));
  assert.ok(fs.existsSync(path.join(root, "assets/direction/ai-content-brand.jpg")));
  assert.ok(fs.existsSync(path.join(root, "assets/direction/ai-monetization-analysis.jpg")));
  assert.doesNotMatch(principlesHtml, /principles-avatar/);
  assert.doesNotMatch(principlesHtml, /circular-gallery/);
  assert.doesNotMatch(principlesHtml, /data-circular-gallery/);
  assert.doesNotMatch(principlesHtml, /data-gallery-card/);
  assert.doesNotMatch(principlesHtml, /quote-stack-card/);
  assert.match(html, /我关注的方向/);
  assert.match(html, /<section class="about-section project-spiral-section" id="projects" aria-labelledby="projects-title">/);
  assert.match(html, /<h1 id="projects-title"><span aria-hidden="true">↘<\/span> 我正在做的项目<\/h1>/);
  assert.doesNotMatch(html, /id="about-title"/);
  assert.match(html, /class="project-spiral-stage"[\s\S]*data-project-spiral[\s\S]*aria-label="Project spiral animation"/);
  assert.match(html, /<img class="project-ascii-portrait" src="assets\/projects\/ascii-portrait\.png" alt="ASCII portrait of Ninghuohuo">/);
  assert.match(html, /<div class="project-spiral-arrow" data-project-spiral-arrow aria-hidden="true"><\/div>/);
  assert.doesNotMatch(html, /data-project-laptop/);
  assert.doesNotMatch(html, /project-laptop\.js/);
  assert.doesNotMatch(html, /assets\/projects\/laptop\.glb/);
  assert.doesNotMatch(html, /project-ascii-workbench/);
  assert.doesNotMatch(html, /project-ascii-laptop/);
  assert.doesNotMatch(html, /data-project-ascii-portrait/);
  assert.match(html, /class="project-spiral-perspective"[^>]*style="perspective: 1200px; perspective-origin: right center;"/);
  assert.match(html, /class="project-spiral-track"[^>]*style="transform-style: preserve-3d;"/);
  assert.doesNotMatch(html, /BUILDING NOW/);
  assert.doesNotMatch(html, /data-project-3d-list/);
  assert.doesNotMatch(html, /class="project-3d-item" data-project-3d-item/);
  assert.doesNotMatch(html, /data-circular-gallery/);
  assert.doesNotMatch(html, /project-gallery/);
  assert.doesNotMatch(html, /data-gallery-card/);
  assert.match(html, /<section class="hobby-section" id="hobbies" aria-labelledby="hobby-title">/);
  assert.match(html, /<h1 id="hobby-title"><span aria-hidden="true">↘<\/span> 我最近的偏好<\/h1>/);
  assert.match(html, /class="hobby-grid"/);
  assert.equal((html.match(/class="hobby-card"/g) || []).length, 5);
  assert.match(html, /<h2>播客\/访谈<\/h2>/);
  assert.match(html, /<h2>健身<\/h2>/);
  assert.match(html, /<h2>爬山<\/h2>/);
  assert.match(html, /<h2>VibeCoding<\/h2>/);
  assert.match(html, /<h2>学习\/搭建工作流<\/h2>/);
  assert.doesNotMatch(html, /data-hobby/);
  assert.doesNotMatch(html, /hobby-card[^>]+data-/);
  assert.doesNotMatch(html, /观察 AI 产品/);
  assert.doesNotMatch(html, /搭自动化流程/);
  assert.doesNotMatch(html, /记录日常灵感/);
  assert.ok(
    html.indexOf('<section class="about-section" id="projects"') < html.indexOf('<section class="hobby-section" id="hobbies"'),
    "hobby section should follow current projects"
  );
  assert.ok(
    html.indexOf('<section class="hobby-section" id="hobbies"') < html.indexOf('<section class="energy-section" id="energy"'),
    "hobby section should sit before energy"
  );
  assert.doesNotMatch(html, /Born in Brazil/i);
  assert.doesNotMatch(html, /Stuff I'm good at/);
  assert.doesNotMatch(html, /portrait-main/);
  assert.doesNotMatch(html, /portrait-small/);
  assert.match(html, /<footer class="site-footer" id="contact">/);
  assert.match(html, /<h1>联系我<\/h1>/);
  assert.match(html, /class="footer-pixel-flower" aria-hidden="true"/);
  assert.match(html, /<img src="assets\/principles\/pixel-flower-transparent\.png" alt="">/);
  assert.match(html, /<p class="footer-since">From 2026 onwards<\/p>/);
  assert.doesNotMatch(html, /CONTACT/);
  assert.match(html, /一起学习和聊聊 AI、内容、产品，或者任何正在成形的想法。/);
  assert.match(html, /class="footer-note" data-decrypted-text/);
  assert.match(html, /mailto:hello@ninghuo\.ai/);
  assert.match(html, />MAIL<\/span>/);
  assert.match(html, />WECHAT<\/span>/);
  assert.match(html, />DOUYIN<\/span>/);
  assert.match(html, />XIAOHONGSHU<\/span>/);
  assert.match(html, />BILIBILI<\/span>/);
  assert.match(html, />X<\/span>/);
  assert.match(html, />YOUTUBE<\/span>/);
  assert.match(html, /class="footer-contact-panel"/);
  assert.equal((html.match(/class="footer-contact-row/g) || []).length, 7);
  assert.doesNotMatch(html, /class="contact-name variable-proximity-demo"/);
  assert.doesNotMatch(html, /class="footer-social-icon/);
  assert.match(html, /https:\/\/www\.douyin\.com\/user\/MS4wLjABAAAAw9ywuB5SWYQunLp7siyFuipj-Q9-B-ieWHOaLx_zQ7fnmJBlBzncI5t-zri2LrbK\?from_tab_name=main/);
  assert.match(html, /https:\/\/www\.xiaohongshu\.com\/user\/profile\/56e9201084edcd534c0d2a58\?xsec_token=ABrA-pD3uX6NkUTH52r9fyBOUeUEl5iuR2ArtB-Rq8nKo=&amp;xsec_source=pc_search/);
  assert.match(html, /https:\/\/space\.bilibili\.com\/3706949981964329\?spm_id_from=333\.337\.0\.0/);
  assert.match(html, /https:\/\/x\.com\/search\?q=%E5%AE%81%E7%81%AB%E7%81%AB&amp;src=typed_query&amp;f=user/);
  assert.match(html, /https:\/\/www\.youtube\.com\/results\?search_query=%E5%AE%81%E7%81%AB%E7%81%AB/);
  assert.match(html, /data-wechat-modal-open/);
  assert.match(html, /data-wechat-modal-close/);
  assert.match(html, /class="footer-qr-grid"/);
  assert.match(html, /src="assets\/contact\/wechat-personal-qr\.png"/);
  assert.match(html, /src="assets\/contact\/wechat-group-qr\.png"/);
  assert.match(html, /个人微信/);
  assert.match(html, /微信群聊/);
  assert.match(html, /aria-label="微信二维码"/);
  assert.doesNotMatch(html, /aria-label="微信公众号"/);
  assert.doesNotMatch(html, /Agencies<br>&amp; Clients/i);
  assert.doesNotMatch(html, /This is not finished/i);
  assert.doesNotMatch(html, /logo-strip/);
  assert.doesNotMatch(html, /history\.scrollRestoration = "manual"/);
  assert.doesNotMatch(html, /if \(window\.location\.hash\)/);
  assert.equal((html.match(/class="scroll-stack-card safari-window/g) || []).length, 0);
  assert.doesNotMatch(html, /safari-window[^>]*>\s*<img/s);
  assert.match(css, /html\s*{[^}]*background:\s*var\(--white\);/s);
  assert.match(css, /html,\s*body\s*{[^}]*overflow-x:\s*clip;/s);
  assert.match(css, /body\s*{[^}]*background:\s*var\(--white\);/s);
  assert.match(css, /body\s*{[^}]*min-height:\s*100svh;[^}]*overflow-y:\s*auto;/s);
  assert.doesNotMatch(css, /body:not\(\.is-inside-computer\)\s*{/);
  assert.doesNotMatch(css, /body:not\(\.is-inside-computer\) \.page-stack/);
  assert.doesNotMatch(css, /body\.is-inside-computer:not\(\.is-three-flight\) \.hero-page/);
  assert.match(css, /\.hero-pin\s*{[^}]*position:\s*relative;[^}]*height:\s*200svh;[^}]*z-index:\s*1;/s);
  assert.match(css, /\.hero-page\s*{[^}]*height:\s*100svh;[^}]*min-height:\s*100svh;[^}]*overflow:\s*hidden;[^}]*position:\s*fixed;[^}]*top:\s*0;[^}]*left:\s*0;[^}]*right:\s*0;/s);
  assert.match(css, /body\.is-past-hero \.hero-page\s*{[^}]*visibility:\s*hidden;[^}]*pointer-events:\s*none;/s);
  assert.match(css, /\.hero-portrait\s*{[^}]*position:\s*absolute;[^}]*top:\s*14px;[^}]*left:\s*14px;/s);
  assert.match(css, /\.hero-computer\s*{[^}]*position:\s*absolute;[^}]*top:\s*clamp\(70px, 6\.3vw, 112px\);[^}]*left:\s*clamp\(0px, 2vw, 42px\);[^}]*width:\s*clamp\(260px, 23vw, 454px\);[^}]*aspect-ratio:\s*1\.28 \/ 1;/s);
  assert.match(css, /@media \(max-width: 760px\)[\s\S]*\.hero-computer\s*{[^}]*top:\s*58px;[^}]*left:\s*18px;[^}]*width:\s*230px;/s);
  assert.match(css, /\.hero-computer canvas\s*{[^}]*display:\s*block;[^}]*width:\s*100%;[^}]*height:\s*100%;/s);
  assert.match(css, /\.hero-portrait img\s*{[^}]*object-position:\s*50% 42%;/s);
  assert.match(css, /\.tilted-card-figure\s*{[^}]*perspective:\s*800px;/s);
  assert.match(css, /\.tilted-card-inner\s*{[^}]*transform-style:\s*preserve-3d;/s);
  assert.match(css, /\.tilted-card-img\s*{[^}]*will-change:\s*transform;/s);
  assert.match(css, /\.tilted-card-caption\s*{[^}]*pointer-events:\s*none;/s);
  assert.match(css, /\.hero-clock\s*{[^}]*position:\s*absolute;[^}]*top:\s*16px;[^}]*left:\s*50%;/s);
  assert.match(css, /\.hero-clock\s*{[^}]*font-size:\s*clamp\(15px, 1\.1vw, 21px\);[^}]*font-weight:\s*400;/s);
  assert.match(css, /\.hero-greeting\s*{[^}]*position:\s*absolute;[^}]*left:\s*24px;[^}]*bottom:\s*clamp\(382px, 45vh, 562px\);/s);
  assert.match(css, /\.text-type\s*{[^}]*display:\s*inline-block;[^}]*white-space:\s*pre-wrap;/s);
  assert.match(css, /\.text-type__content\s*{[^}]*display:\s*inline;/s);
  assert.match(css, /\.text-type__cursor\s*{[^}]*margin-left:\s*0\.25rem;[^}]*animation:\s*cursor-blink/s);
  assert.match(css, /\.hero-intro-copy\s*{[^}]*position:\s*absolute;[^}]*left:\s*24px;[^}]*bottom:\s*clamp\(270px, 36vh, 465px\);/s);
  assert.match(css, /\.hero-intro-copy\s*{[^}]*font-size:\s*clamp\(14px, \.98vw, 20px\);[^}]*font-weight:\s*400;[^}]*line-height:\s*1\.32;[^}]*text-align:\s*left;/s);
  assert.match(css, /\.hero-intro-copy p\s*{[^}]*margin:\s*0;[^}]*text-indent:\s*clamp\(82px, 8vw, 150px\);/s);
  assert.match(css, /\.site-header nav\s*{[^}]*font-size:\s*clamp\(14px, 1vw, 20px\);[^}]*font-weight:\s*400;/s);
  assert.match(css, /\.site-header nav a::after\s*{[^}]*left:\s*50%;[^}]*right:\s*50%;[^}]*height:\s*1px;[^}]*transition:/s);
  assert.match(css, /\.site-header nav a:hover::after,[\s\S]*\.site-header nav a:focus-visible::after\s*{[^}]*left:\s*0;[^}]*right:\s*0;/s);
  assert.match(css, /@import url\('https:\/\/fonts\.googleapis\.com\/css2\?family=Roboto\+Flex:opsz,wght@8\.\.144,100\.\.1000&display=swap'\);/);
  assert.match(css, /\.hero-name\s*{[^}]*display:\s*flex;[^}]*justify-content:\s*space-between;[^}]*color:\s*var\(--black\);/s);
  assert.match(css, /\.hero-name\s*{[^}]*font-family:\s*'Roboto Flex', Arial, Helvetica, sans-serif;[^}]*font-size:\s*clamp\(58px, 13\.6vw, 430px\);/s);
  assert.doesNotMatch(css, /\.contact-name/);
  assert.match(css, /\.hero-name\s*{[^}]*position:\s*absolute;[^}]*left:\s*clamp\(18px, 1\.8vw, 34px\);[^}]*right:\s*clamp\(18px, 1\.8vw, 34px\);[^}]*bottom:\s*clamp\(20px, 2\.6vh, 35px\);/s);
  assert.match(css, /\.variable-proximity-letter\s*{[^}]*display:\s*inline-block;[^}]*font-variation-settings:\s*'wght' 700, 'opsz' 8;/s);
  assert.match(css, /\.sr-only\s*{[^}]*position:\s*absolute;[^}]*width:\s*1px;[^}]*height:\s*1px;[^}]*clip:\s*rect\(0, 0, 0, 0\);/s);
  assert.doesNotMatch(css, /\.split-char/);
  assert.match(css, /#direction\s*{[^}]*min-height:\s*calc\(200svh \+ var\(--direction-copy-height, 0px\)\);[^}]*padding:\s*0;/s);
  assert.match(css, /\.direction-reveal-content\s*{[^}]*position:\s*absolute;[^}]*top:\s*0;[^}]*left:\s*0;[^}]*right:\s*0;[^}]*min-height:\s*100svh;[^}]*height:\s*auto;[^}]*padding:\s*0 0 clamp\(42px, 5vw, 72px\);[^}]*overflow:\s*visible;/s);
  assert.match(css, /\.brag-zone\.is-direction-reveal-active \.direction-reveal-content\s*{[^}]*position:\s*fixed;[^}]*top:\s*0;[^}]*left:\s*0;[^}]*right:\s*0;/s);
  assert.match(css, /\.brag-zone\.is-direction-reveal-after \.direction-reveal-content\s*{[^}]*position:\s*absolute;[^}]*top:\s*auto;[^}]*bottom:\s*0;[^}]*left:\s*0;[^}]*right:\s*0;/s);
  assert.match(css, /\.direction-single\s*{[^}]*display:\s*grid;[^}]*width:\s*100%;[^}]*max-width:\s*none;[^}]*margin:\s*0;/s);
  assert.match(css, /\.direction-feature\s*{[^}]*width:\s*100%;[^}]*height:\s*100svh;[^}]*min-height:\s*100svh;[^}]*overflow:\s*hidden;/s);
  assert.match(css, /\.direction-feature img\s*{[^}]*width:\s*100%;[^}]*height:\s*100%;[^}]*object-fit:\s*cover;[^}]*filter:\s*saturate\(\.88\) contrast\(1\.06\) brightness\(\.82\);/s);
  assert.match(css, /\.direction-copy\s*{[^}]*justify-items:\s*start;[^}]*width:\s*min\(1040px, calc\(60vw - 32px\)\);[^}]*margin-left:\s*40vw;[^}]*padding:\s*clamp\(26px, 3\.2vw, 52px\) 0 0 clamp\(16px, 2\.2vw, 44px\);[^}]*text-align:\s*left;/s);
  assert.match(css, /\.direction-copy h1\s*{[^}]*font-weight:\s*400;[^}]*text-align:\s*left;/s);
  assert.match(css, /\.direction-topic-list\s*{[^}]*display:\s*grid;[^}]*grid-template-columns:\s*1fr;[^}]*justify-items:\s*start;[^}]*gap:\s*clamp\(52px, 5\.4vw, 96px\);[^}]*margin-top:\s*clamp\(92px, 8vw, 160px\);/s);
  assert.match(css, /\.direction-topic\s*{[^}]*display:\s*grid;[^}]*grid-template-columns:\s*auto minmax\(0, 1fr\);[^}]*justify-items:\s*start;[^}]*row-gap:\s*clamp\(2px, \.35vw, 6px\);[^}]*text-align:\s*left;/s);
  assert.match(css, /\.direction-topic h2,[\s\S]*\.direction-topic p\s*{[^}]*font-weight:\s*400;/s);
  assert.match(css, /\.direction-topic h2\s*{[^}]*display:\s*grid;[^}]*font-size:\s*clamp\(18px, 1\.35vw, 26px\);[^}]*font-weight:\s*400;/s);
  assert.match(css, /\.direction-topic p\s*{[^}]*color:\s*var\(--white\);[^}]*font-size:\s*clamp\(18px, 1\.35vw, 26px\);/s);
  assert.match(css, /\.direction-topic p\[lang="en"\]\s*{[^}]*grid-column:\s*2;[^}]*color:\s*var\(--white\);/s);
  assert.doesNotMatch(css, /\.direction-collage-item:hover/);
  assert.doesNotMatch(css, /\.direction-hover-overlay/);
  assert.doesNotMatch(css, /\.direction-marquee/);
  assert.doesNotMatch(css, /@keyframes direction-marquee-scroll/);
  assert.doesNotMatch(css, /\.card-swap-container/);
  assert.doesNotMatch(css, /\.direction-card/);
  assert.match(css, /\.safari-window\s*{[^}]*border-radius:\s*32px;[^}]*box-shadow:/s);
  assert.match(css, /\.safari-window-chrome\s*{[^}]*display:\s*grid;[^}]*grid-template-columns:\s*auto 1fr auto;/s);
  assert.match(css, /\.safari-address\s*{[^}]*border-radius:\s*999px;/s);
  assert.match(css, /\.project-summary\s*{[^}]*opacity:\s*1;/s);
  assert.match(css, /\.project-tile-lime,\s*\.project-tile-sky,\s*\.project-tile-pink,\s*\.project-tile-violet\s*{[^}]*background:\s*var\(--white\);/s);
  assert.doesNotMatch(css, /\.edge-marks/);
  assert.doesNotMatch(css, /\.project-tile-(?:lime|sky|pink|violet)\s*{[^}]*#(?:d7ff43|6dd8ff|ff7ab8|8f78ff)/s);
  assert.doesNotMatch(css, /\.project-tile:hover \.project-summary/s);
  assert.match(css, /\.about-section\s*{[^}]*min-height:\s*100svh;[^}]*padding:\s*0;/s);
  assert.match(css, /\.project-spiral-section\s*{[^}]*position:\s*relative;[^}]*margin-top:\s*0;[^}]*height:\s*100svh;[^}]*background:\s*var\(--white\);[^}]*overflow:\s*hidden;/s);
  assert.match(css, /\.project-spiral-section h1\s*{[^}]*position:\s*absolute;[^}]*z-index:\s*2;/s);
  assert.match(css, /\.brag-zone h1,[\s\S]*\.project-spiral-section h1,[\s\S]*\.energy-section h1\s*{[^}]*font-size:\s*clamp\(24px, 3vw, 34px\);/s);
  assert.match(css, /\.project-spiral-stage\s*{[^}]*width:\s*100%;[^}]*height:\s*100svh;[^}]*overflow:\s*hidden;[^}]*user-select:\s*none;/s);
  assert.match(css, /\.project-ascii-portrait\s*{[^}]*position:\s*absolute;[^}]*left:\s*clamp\(128px, 12\.8vw, 270px\);[^}]*bottom:\s*0;[^}]*width:\s*clamp\(364px, 37\.7vw, 767px\);[^}]*height:\s*min\(112vh, 1170px\);[^}]*object-position:\s*center bottom;/s);
  assert.doesNotMatch(css, /\.project-laptop-model/);
  assert.doesNotMatch(css, /\.project-laptop-debug/);
  assert.match(css, /\.project-spiral-arrow\s*{[^}]*position:\s*absolute;[^}]*top:\s*45%;[^}]*right:\s*clamp\(30px, 5\.8vw, 118px\);[^}]*opacity:\s*0;/s);
  assert.match(css, /\.project-spiral-arrow::before\s*{[^}]*clip-path:\s*polygon\(/s);
  assert.doesNotMatch(css, /\.project-spiral-arrow::after\s*{/);
  assert.match(css, /\.project-spiral-stage\.is-active \.project-spiral-arrow\s*{[^}]*opacity:\s*1;/s);
  assert.match(css, /\.project-spiral-stage\.is-pushing \.project-spiral-item\.is-current \.project-spiral-title,[\s\S]*\.project-spiral-stage\.is-pushing \.project-spiral-item\.is-current \.project-spiral-desc\s*{[^}]*animation:\s*project-spiral-copy-push \.64s/s);
  assert.match(css, /@keyframes project-spiral-arrow-push/);
  assert.match(css, /@keyframes project-spiral-copy-push/);
  assert.doesNotMatch(css, /project-ascii-portrait-text/);
  assert.doesNotMatch(css, /project-ascii-laptop/);
  assert.doesNotMatch(css, /ascii-key-line/);
  assert.doesNotMatch(html, /ascii-hand/);
  assert.doesNotMatch(css, /@keyframes ascii-left-hand-type/);
  assert.doesNotMatch(css, /@keyframes ascii-right-hand-type/);
  assert.match(css, /\.project-spiral-perspective\s*{[^}]*perspective:\s*1200px;[^}]*perspective-origin:\s*right center;/s);
  assert.match(css, /\.project-spiral-track\s*{[^}]*transform-style:\s*preserve-3d;/s);
  assert.match(css, /\.project-spiral-item\s*{[^}]*position:\s*absolute;[^}]*top:\s*50%;[^}]*right:\s*12vw;[^}]*transform-origin:\s*right center;/s);
  assert.match(css, /\.project-spiral-title\s*{[^}]*text-align:\s*right;/s);
  assert.match(css, /\.project-spiral-desc\s*{[^}]*text-align:\s*right;/s);
  assert.match(css, /\.project-spiral-title\s*{[^}]*font-size:\s*clamp\(52px, 10vh, 116px\);[^}]*font-weight:\s*700;/s);
  assert.match(css, /\.project-spiral-desc\s*{[^}]*font-size:\s*clamp\(16px, 3vh, 34px\);[^}]*font-weight:\s*500;/s);
  assert.doesNotMatch(css, /\.project-3d-/);
  assert.match(css, /\.about-copy\s*{[^}]*padding-top:\s*0;/s);
  assert.match(css, /\.about-copy h1,[\s\S]*\.site-footer h1\s*{[^}]*font-size:\s*clamp\(24px, 3vw, 34px\);/s);
  assert.match(css, /\.build-project-list\s*{[^}]*border-top:\s*1px solid var\(--line\);/s);
  assert.match(css, /\.build-project\s*{[^}]*display:\s*grid;[^}]*grid-template-columns:\s*minmax\(150px, \.72fr\) 1fr;/s);
  assert.match(css, /\.hobby-section\s*{[^}]*position:\s*relative;[^}]*min-height:\s*100svh;[^}]*padding:\s*93px 10px 96px;[^}]*background:\s*#EBEBEB;[^}]*color:\s*var\(--black\);/s);
  assert.match(css, /\.hobby-grid\s*{[^}]*display:\s*grid;[^}]*grid-template-columns:\s*repeat\(3, minmax\(0, 1fr\)\);/s);
  assert.match(css, /\.hobby-card\s*{[^}]*min-height:\s*clamp\(240px, 24vw, 360px\);/s);
  assert.doesNotMatch(css, /\.hobby-card\s*{[^}]*border-top:/s);
  assert.doesNotMatch(css, /\.hobby-card\s*{[^}]*border-bottom:/s);
  assert.match(css, /\.page-stack\s*{[^}]*position:\s*relative;[^}]*z-index:\s*3;[^}]*margin-top:\s*-100svh;/s);
  assert.doesNotMatch(css, /body\.is-three-flight/);
  assert.doesNotMatch(css, /--hero-flight-/);
  assert.doesNotMatch(css, /--hero-enter-/);
  assert.doesNotMatch(css, /--depth-fade-opacity/);
  assert.doesNotMatch(css, /\.screen-depth-fade/);
  assert.match(css, /\.manifesto-copy\s*{[^}]*width:\s*100%;[^}]*max-width:\s*none;/s);
  assert.match(css, /\.manifesto\s*{[^}]*position:\s*relative;[^}]*z-index:\s*3;[^}]*margin-top:\s*-1px;/s);
  assert.match(css, /\.scroll-reveal\s*{[^}]*margin:\s*20px 0;/s);
  assert.match(css, /\.scroll-reveal-text\s*{[^}]*font-size:\s*clamp\(1\.6rem, 4vw, 3rem\);[^}]*line-height:\s*1\.5;[^}]*font-weight:\s*600;/s);
  assert.match(css, /\.manifesto-copy\.scroll-reveal\s*{[^}]*margin:\s*0;/s);
  assert.match(css, /\.manifesto-en\s*{[^}]*line-height:\s*\.96;/s);
  assert.match(css, /\.manifesto-zh\s*{[^}]*margin-top:\s*clamp\(68px, 6\.2vw, 112px\);[^}]*font-size:\s*clamp\(24px, 3\.05vw, 44px\);/s);
  assert.match(css, /\.energy-section\s*{[^}]*position:\s*relative;[^}]*min-height:\s*100svh;[^}]*padding:\s*93px 10px 96px;[^}]*background:\s*var\(--black\);[^}]*color:\s*var\(--white\);/s);
  assert.match(css, /\.energy-section h1\s*{[^}]*position:\s*relative;[^}]*z-index:\s*2;/s);
  assert.match(css, /\.energy-stage\s*{[^}]*position:\s*absolute;[^}]*inset:\s*0;[^}]*z-index:\s*1;[^}]*min-height:\s*calc\(100svh - 160px\);/s);
  assert.match(css, /\.particles-container\s*{[^}]*position:\s*relative;[^}]*width:\s*100%;[^}]*height:\s*100%;/s);
  assert.match(css, /\.energy-particles canvas\s*{[^}]*display:\s*block;[^}]*width:\s*100%;[^}]*height:\s*100%;/s);
  assert.match(css, /\.brag-zone h1,[\s\S]*\.energy-section h1\s*{[^}]*font-size:\s*clamp\(24px, 3vw, 34px\);/s);
  assert.match(css, /\.brag-zone\s*{[^}]*position:\s*relative;[^}]*z-index:\s*1;[^}]*min-height:\s*200svh;[^}]*margin-top:\s*-100svh;[^}]*padding:\s*0;[^}]*background:\s*var\(--black\);[^}]*color:\s*var\(--white\);[^}]*overflow:\s*visible;/s);
  assert.doesNotMatch(css, /\.direction-pin/);
  assert.doesNotMatch(css, /--direction-pin-height/);
  assert.doesNotMatch(css, /\.direction-scroll-content/);
  assert.match(css, /\.selected-projects\s*{[^}]*position:\s*relative;[^}]*z-index:\s*2;[^}]*min-height:\s*calc\(100svh \+ var\(--principles-flow-distance, 2600px\)\);[^}]*overflow:\s*visible;[^}]*background:\s*var\(--white\);[^}]*color:\s*var\(--black\);/s);
  assert.match(css, /\.principles-sticky\s*{[^}]*position:\s*absolute;[^}]*top:\s*0;[^}]*left:\s*0;[^}]*right:\s*0;[^}]*min-height:\s*100svh;[^}]*height:\s*100svh;[^}]*padding:\s*87px 8px 0;[^}]*overflow:\s*hidden;/s);
  assert.match(css, /\.selected-projects\.is-principles-pinned \.principles-sticky\s*{[^}]*position:\s*fixed;[^}]*top:\s*0;[^}]*left:\s*0;[^}]*right:\s*0;/s);
  assert.match(css, /\.selected-projects\.is-principles-after \.principles-sticky\s*{[^}]*position:\s*absolute;[^}]*top:\s*auto;[^}]*bottom:\s*0;/s);
  assert.match(css, /\.selected-projects h1\s*{[^}]*position:\s*relative;[^}]*z-index:\s*3;[^}]*font-weight:\s*700;/s);
  assert.match(css, /\.principles-intro-copy\s*{[^}]*position:\s*absolute;[^}]*left:\s*clamp\(39px, calc\(21px \+ 2\.25vw\), 51px\);[^}]*top:\s*clamp\(190px, 19vh, 270px\);[^}]*z-index:\s*3;[^}]*width:\s*clamp\(192px, 19\.9vw, 272px\);[^}]*max-width:\s*calc\(100vw - 16px\);[^}]*font-size:\s*clamp\(14px, \.98vw, 20px\);[^}]*font-weight:\s*400;[^}]*line-height:\s*1\.32;/s);
  assert.doesNotMatch(css, /\.principles-pixel-flower/);
  assert.doesNotMatch(css, /@keyframes principles-pixel-flower-float/);
  assert.match(css, /\.principles-scroll-stage\s*{[^}]*position:\s*absolute;[^}]*inset:\s*0;[^}]*z-index:\s*2;/s);
  assert.match(css, /\.selected-projects\.is-in-view \.principles-scroll-stage\s*{[^}]*opacity:\s*1;[^}]*transform:\s*translate3d\(0, 0, 0\);/s);
  assert.match(css, /\.principles-track\s*{[^}]*position:\s*absolute;[^}]*left:\s*0;[^}]*right:\s*0;[^}]*top:\s*0;[^}]*display:\s*grid;[^}]*row-gap:\s*clamp\(88px, 10vh, 128px\);[^}]*padding-top:\s*clamp\(210px, 25vh, 310px\);[^}]*transform:\s*translate3d\(0, var\(--principles-flow-y, 0px\), 0\);/s);
  assert.match(css, /\.principles-slide\s*{[^}]*position:\s*relative;[^}]*min-height:\s*0;[^}]*opacity:\s*1;[^}]*visibility:\s*visible;/s);
  assert.doesNotMatch(css, /\.principles-slide\.is-active\s*{/);
  assert.match(css, /\.principles-copy\s*{[^}]*position:\s*relative;[^}]*margin-left:\s*50%;[^}]*width:\s*clamp\(240px, 24vw, 360px\);[^}]*font-size:\s*clamp\(14px, \.98vw, 20px\);/s);
  assert.match(css, /\.principles-photo-card\s*{[^}]*position:\s*absolute;[^}]*right:\s*clamp\(39px, calc\(21px \+ 2\.25vw\), 51px\);[^}]*top:\s*0;[^}]*width:\s*clamp\(105px, 12vw, 195px\);/s);
  assert.match(css, /\.principles-role\s*{[^}]*margin:\s*clamp\(8px, \.85vw, 14px\) 0 0;/s);
  assert.match(css, /\.principles-quote\s*{[^}]*gap:\s*clamp\(12px, 1\.3vw, 22px\);[^}]*margin:\s*clamp\(17px, 2vw, 28px\) 0 0;[^}]*font-size:\s*clamp\(24px, 1\.65vw, 34px\);[^}]*font-weight:\s*700;/s);
  assert.doesNotMatch(css, /\.principles-scrambled-text/);
  assert.doesNotMatch(css, /\.scrambled-char/);
  assert.match(css, /\.principles-decay-filters\s*{[^}]*position:\s*fixed;[^}]*width:\s*0;[^}]*height:\s*0;[^}]*overflow:\s*hidden;[^}]*pointer-events:\s*none;/s);
  assert.doesNotMatch(css, /\.principles-progress\s*{/);
  assert.doesNotMatch(css, /\.principles-pinboard/);
  assert.doesNotMatch(css, /\.principles-note\s*{/);
  assert.doesNotMatch(css, /\.principles-pin\s*{/);
  assert.doesNotMatch(css, /\.principles-polaroid\s*{/);
  assert.doesNotMatch(css, /\.principles-macbook/);
  assert.doesNotMatch(css, /\.principles-macbook-screen/);
  assert.doesNotMatch(css, /\.principles-macbook-camera/);
  assert.doesNotMatch(css, /\.principles-macbook-base/);
  assert.match(css, /\.principles-slide/);
  assert.match(css, /\.content\s*{[^}]*position:\s*relative;/s);
  assert.doesNotMatch(css, /\.principles-decay-card\s*{/);
  assert.doesNotMatch(css, /\.principles-decay-stack\s*{/);
  assert.doesNotMatch(css, /\.principles-decay-stack-card\s*{/);
  assert.doesNotMatch(css, /\.principles-person-meta/);
  assert.doesNotMatch(css, /\.principles-controls/);
  assert.doesNotMatch(css, /\.principles-progress-button/);
  assert.doesNotMatch(css, /\.stack-container/);
  assert.doesNotMatch(css, /\.card-rotate/);
  assert.doesNotMatch(css, /\.principles-tilted-card\s*{/);
  assert.doesNotMatch(css, /\.principles-tilted-card-inner\s*{/);
  assert.doesNotMatch(css, /\.principles-photo-placeholder\s*{/);
  assert.match(css, /\.principles-quote-en\s*{[^}]*font-size:\s*inherit;[^}]*font-weight:\s*700;/s);
  assert.match(css, /@media \(max-width: 860px\)\s*{[^}]*\.principles-copy\s*{[^}]*margin-left:\s*34vw;/s);
  assert.doesNotMatch(css, /@keyframes principles-progress-fill/);
  assert.doesNotMatch(css, /\.project-gallery\s*{/);
  assert.doesNotMatch(css, /\.project-gallery-fallback\s*{/);
  assert.doesNotMatch(script, /initCardSwap/);
  assert.doesNotMatch(script, /data-card-swap/);
  assert.doesNotMatch(script, /direction-card/);
  assert.match(script, /new IntersectionObserver/);
  assert.doesNotMatch(script, /rootMargin:\s*"180px 0px 180px 0px"/);
  assert.doesNotMatch(script, /runInit\("card swap"/);
  assert.match(script, /const initProjectSpiral = \(\) =>/);
  assert.match(script, /querySelectorAll\("\[data-project-spiral\]"\)/);
  assert.match(script, /const projectSpiralBaseItems = \[/);
  assert.match(script, /const totalItems = 300;/);
  assert.match(script, /const startIndex = 150;/);
  assert.match(script, /const autoDelay = 2500;/);
  assert.doesNotMatch(script, /wheelThrottle/);
  assert.match(script, /const itemSpacing = 22;/);
  assert.match(script, /const rotateX = offset \* 5;/);
  assert.match(script, /transformOrigin = "right center"/);
  assert.match(script, /const rotateY = offset \* -32;/);
  assert.match(script, /const rotateZ = offset \* -6;/);
  assert.doesNotMatch(script, /stage\.addEventListener\("wheel"/);
  assert.doesNotMatch(script, /stage\.addEventListener\("wheel"/);
  assert.match(script, /runInit\("project spiral", initProjectSpiral\)/);
  assert.doesNotMatch(script, /initProjectAsciiPortrait/);
  assert.doesNotMatch(script, /projectAsciiPortrait/);
  assert.doesNotMatch(script, /initProject3DList/);
  assert.doesNotMatch(script, /const initDirectionCards = \(\) =>/);
  assert.doesNotMatch(css, /\.project-gallery\s*{[^}]*margin-top:\s*33px;/s);
  assert.doesNotMatch(css, /\.stack-card-rotate/);
  assert.match(css, /\.quote-stack-card\s*{[^}]*border:\s*2px solid var\(--black\);[^}]*border-radius:\s*8px;/s);
  assert.doesNotMatch(css, /\.selected-projects h1\s*{[^}]*font-weight:\s*400;/s);
  assert.match(css, /\.quote-person strong\s*{[^}]*font-weight:\s*400;/s);
  assert.match(css, /\.quote-person small\s*{[^}]*font-weight:\s*400;/s);
  assert.match(css, /blockquote\s*{[^}]*font-weight:\s*400;/s);
  assert.match(css, /\.site-footer\s*{[^}]*position:\s*relative;[^}]*z-index:\s*3;[^}]*min-height:\s*100svh;[^}]*padding:\s*93px 10px 28px;[^}]*background:\s*var\(--white\);[^}]*color:\s*var\(--black\);/s);
  assert.match(css, /\.footer-line\s*{[^}]*min-height:\s*calc\(100svh - 90px\);[^}]*align-items:\s*start;[^}]*justify-items:\s*center;[^}]*padding-top:\s*clamp\(18px, 3vh, 40px\);/s);
  assert.match(css, /\.decrypted-text__char--encrypted\s*{[^}]*color:\s*rgba\(0, 0, 0, \.52\);/s);
  assert.doesNotMatch(css, /\.site-footer h1\s*{[^}]*font-size:\s*clamp\(44px, 6vw, 86px\);/s);
  assert.match(css, /\.footer-since\s*{[^}]*position:\s*absolute;[^}]*left:\s*50%;[^}]*bottom:\s*10px;[^}]*transform:\s*translateX\(-50%\);[^}]*font-size:\s*clamp\(10px, \.75vw, 13px\);/s);
  assert.match(css, /\.footer-pixel-flower\s*{[^}]*position:\s*absolute;[^}]*left:\s*50%;[^}]*bottom:\s*clamp\(38px, 4vh, 60px\);[^}]*z-index:\s*2;[^}]*width:\s*clamp\(48px, 4vw, 82px\);[^}]*transform:\s*translateX\(-50%\);/s);
  assert.match(css, /\.footer-pixel-flower img\s*{[^}]*image-rendering:\s*pixelated;[^}]*image-rendering:\s*crisp-edges;/s);
  assert.doesNotMatch(css, /\.footer-pixel-flower\s*{[^}]*animation:/s);
  assert.match(css, /\.footer-contact-panel\s*{[^}]*display:\s*grid;[^}]*justify-items:\s*center;[^}]*width:\s*min\(520px, calc\(100vw - 44px\)\);/s);
  assert.match(css, /\.footer-contact-list\s*{[^}]*display:\s*grid;[^}]*width:\s*100%;/s);
  assert.match(css, /\.footer-contact-list\s*{[^}]*gap:\s*clamp\(16px, 1\.7vw, 28px\);/s);
  assert.match(css, /\.footer-contact-row\s*{[^}]*display:\s*flex;[^}]*justify-content:\s*center;[^}]*border:\s*0;[^}]*font-size:\s*clamp\(18px, 1\.75vw, 28px\);[^}]*font-weight:\s*400;/s);
  assert.doesNotMatch(css, /\.footer-contact-row\s*{[^}]*border-bottom:/s);
  assert.doesNotMatch(css, /\.footer-contact-row::after/);
  assert.doesNotMatch(css, /content:\s*"↗"/);
  assert.match(css, /\.wechat-modal\s*{[^}]*position:\s*fixed;[^}]*inset:\s*0;[^}]*z-index:\s*12000;/s);
  assert.match(css, /\.wechat-modal-panel\s*{[^}]*position:\s*relative;[^}]*width:\s*min\(680px, calc\(100vw - 38px\)\);/s);
  assert.match(css, /\.footer-qr-grid\s*{[^}]*display:\s*flex;[^}]*justify-content:\s*center;/s);
  assert.match(css, /\.footer-qr-card\s*{[^}]*display:\s*grid;[^}]*width:\s*clamp\(118px, 10vw, 156px\);/s);
  assert.match(css, /\.word\s*{[^}]*display:\s*inline-block;/s);
  assert.match(script, /gsap\.registerPlugin\(ScrollTrigger\)/);
  assert.match(particlesScript, /from "https:\/\/cdn\.jsdelivr\.net\/npm\/ogl@1\.0\.11\/src\/index\.js"/);
  assert.match(particlesScript, /const defaultParticleConfig = \{[\s\S]*particleCount:\s*200,[\s\S]*particleSpread:\s*20,[\s\S]*speed:\s*0\.1,[\s\S]*particleBaseSize:\s*100,[\s\S]*moveParticlesOnHover:\s*true,[\s\S]*alphaParticles:\s*false,[\s\S]*disableRotation:\s*false,/s);
  assert.match(particlesScript, /document\.querySelector\("\[data-energy-particles\]"\)/);
  assert.match(particlesScript, /new Geometry\(gl,\s*\{[\s\S]*position:[\s\S]*random:[\s\S]*color:/s);
  assert.match(particlesScript, /requestAnimationFrame\(update\)/);
  assert.deepEqual(orbitScript.match(/assets\/energy\/frame-[\w-]+\.(?:jpg|png)/g), [
    "assets/energy/frame-838.jpg",
    "assets/energy/frame-841.jpg",
    "assets/energy/frame-840-replacement.png",
    "assets/energy/frame-839.jpg",
    "assets/energy/frame-842.jpg"
  ]);
  assert.match(orbitScript, /"frame-838\.jpg":\s*"妈妈"/);
  assert.match(orbitScript, /"frame-839\.jpg":\s*"我"/);
  assert.match(orbitScript, /"frame-840\.jpg":\s*"爸爸"/);
  assert.match(orbitScript, /"frame-841\.jpg":\s*"爷爷"/);
  assert.match(orbitScript, /"frame-842\.jpg":\s*"奶奶"/);
  assert.match(orbitScript, /target\.classList\.contains\("orbit-item"\)/);
  assert.match(orbitScript, /container\.querySelector\("\.orbit-core-images"\)/);
  assert.match(orbitScript, /const unitX = vectorX \/ distance;/);
  assert.match(orbitScript, /driftX = unitX \* travel \+ -unitY \* scatter;/);
  assert.match(orbitScript, /document\.querySelector\("\[data-energy-orbit\]"\)/);
  assert.match(script, /querySelectorAll\("\[data-scroll-reveal\]"\)/);
  assert.doesNotMatch(script, /scrollScrub/);
  assert.equal((script.match(/scrub:\s*true/g) || []).length, 3);
  assert.doesNotMatch(script, /scrollRevealEnterListenerAttached/);
  assert.doesNotMatch(script, /document\.addEventListener\("computer:entered", \(\) => \{/);
  assert.doesNotMatch(script, /dataset\.scrollRevealSplit/);
  assert.doesNotMatch(script, /clearScrollRevealAnimations/);
  assert.doesNotMatch(script, /_scrollRevealAnimations/);
  assert.match(script, /const splitScrollRevealText = \(element\) =>/);
  assert.match(script, /text\.split\(\/\(\\s\+\)\/\)/);
  assert.match(script, /dataset\.scrollRevealAnimated/);
  assert.match(script, /wordAnimationEnd \|\| "bottom bottom"/);
  assert.match(script, /enableBlur = element\.dataset\.enableBlur !== "false"/);
  assert.match(script, /const scroller = window;/);
  assert.match(script, /willChange:\s*"opacity"/);
  assert.match(script, /stagger:\s*0\.05/);
  assert.doesNotMatch(script, /document\.dispatchEvent\(new CustomEvent\("computer:entered"\)\)/);
  assert.doesNotMatch(script, /querySelectorAll\("\[data-split-text\]"\)/);
  assert.doesNotMatch(script, /querySelectorAll\("\[data-fit-text\]"\)/);
  assert.doesNotMatch(script, /const splitChars/);
  assert.doesNotMatch(script, /const initSplitText/);
  assert.doesNotMatch(script, /const fitTextToWidth/);
  assert.doesNotMatch(script, /const initFitText/);
  assert.doesNotMatch(script, /dataset\.fitScale/);
  assert.doesNotMatch(script, /addEventListener\("resize", fitTextToWidth\)/);
  assert.match(script, /const initVariableProximity = \(\) => \{/);
  assert.match(script, /querySelectorAll\("\[data-variable-proximity\]"\)/);
  assert.match(script, /parseFontVariationSettings/);
  assert.match(script, /calculateProximityFalloff/);
  assert.match(script, /let variableProximityFrameId = null;/);
  assert.match(script, /const scheduleVariableProximityUpdate = \(\) =>/);
  assert.match(script, /window\.addEventListener\("mousemove", handleMouseMove, \{ passive: true \}\)/);
  assert.doesNotMatch(script, /window\.requestAnimationFrame\(animateVariableProximity\);\s*\n\s*}\);/);
  assert.match(script, /fontVariationSettings = settings/);
  assert.match(script, /querySelector\("\[data-clock\]"\)/);
  assert.match(script, /setInterval\(updateClock, 1000\)/);
  assert.match(script, /querySelectorAll\("\[data-text-type\]"\)/);
  assert.match(script, /dataset\.textType\.split\("；"\)/);
  assert.match(script, /typingSpeed = 75/);
  assert.match(script, /deletingSpeed = 35/);
  assert.match(script, /pauseDuration = 1500/);
  assert.match(script, /let isDeleting = true/);
  assert.match(script, /displayedText\.slice\(0, -1\)/);
  assert.match(script, /currentTextIndex = \(currentTextIndex \+ 1\) % sentences\.length/);
  assert.match(script, /runInit\("text type", initTextType\)/);
  assert.match(script, /const initPrinciplesScroll = \(\) =>/);
  assert.match(script, /\[data-principles-scroll-stage\]/);
  assert.match(script, /\[data-principles-slide\]/);
  assert.doesNotMatch(script, /\[data-principles-progress\]/);
  assert.doesNotMatch(script, /\[data-principles-toggle\]/);
  assert.match(script, /--principles-flow-distance/);
  assert.match(script, /--principles-flow-y/);
  assert.doesNotMatch(script, /--principles-step-count/);
  assert.doesNotMatch(script, /activeIndex/);
  assert.match(script, /is-principles-pinned/);
  assert.match(script, /is-principles-after/);
  assert.match(script, /window\.addEventListener\("scroll", requestUpdate, \{ passive: true \}\)/);
  assert.match(script, /runInit\("principles scroll", initPrinciplesScroll\)/);
  assert.doesNotMatch(script, /slideDuration = 4200/);
  assert.doesNotMatch(script, /className = "screen-depth-fade"/);
  assert.doesNotMatch(script, /is-inside-computer/);
  assert.doesNotMatch(script, /is-transitioning/);
  assert.doesNotMatch(script, /setHeroFlightFrame/);
  assert.doesNotMatch(script, /window\.setHeroComputerFlightProgress/);
  assert.doesNotMatch(script, /await animate\(0, 1, 760/);
  assert.doesNotMatch(script, /wheelLockedUntil/);
  assert.doesNotMatch(script, /document\.body\.classList\.toggle\("is-three-flight"/);
  assert.doesNotMatch(script, /--hero-flight-/);
  assert.doesNotMatch(script, /cloneNode\(true\)/);
  assert.doesNotMatch(script, /window\.addEventListener\("wheel", handleWheel, \{ passive: false \}\)/);
  assert.doesNotMatch(script, /enterScreen/);
  assert.doesNotMatch(script, /exitScreen/);
  assert.doesNotMatch(script, /const initDampedPageScroll = \(\) =>/);
  assert.doesNotMatch(script, /const damping = 0\.14;/);
  assert.doesNotMatch(script, /const wheelMultiplier = 0\.72;/);
  assert.doesNotMatch(script, /dampedZoneMetrics/);
  assert.doesNotMatch(script, /dampingRelease/);
  assert.doesNotMatch(script, /runInit\("damped page scroll", initDampedPageScroll\)/);
  assert.match(script, /querySelectorAll\("\[data-tilted-card\]"\)/);
  assert.match(script, /dataset\.rotateAmplitude/);
  assert.match(script, /dataset\.scaleOnHover/);
  assert.match(script, /rotateX\(\$\{rotationX\}deg\) rotateY\(\$\{rotationY\}deg\) scale\(\$\{scaleOnHover\}\)/);
  assert.match(script, /runInit\("tilted card", initTiltedCard\)/);
  assert.match(script, /const initPrinciplesDecayCards = \(\) =>/);
  assert.match(script, /\[data-principles-decay-card\]/);
  assert.match(script, /dataset\.principlesDecayDisplacement = "true"/);
  assert.match(script, /maxDisplacement = 220/);
  assert.match(script, /movementBound = 34/);
  assert.match(script, /principles-decay-filter-\$\{index\}/);
  assert.doesNotMatch(script, /const initPrinciplesScrambledText/);
  assert.doesNotMatch(script, /scrambledTextReady/);
  assert.doesNotMatch(script, /runInit\("principles scrambled text"/);
  assert.match(script, /runInit\("principles decay cards", initPrinciplesDecayCards\)/);
  assert.doesNotMatch(script, /principles-macbook-screen/);
  assert.doesNotMatch(script, /const metaHost = carousel;/);
  assert.doesNotMatch(script, /className = "principles-person-meta"/);
  assert.doesNotMatch(script, /updatePersonMeta\(activeIndex\)/);
  assert.doesNotMatch(script, /const initPrinciplesDecayStacks = \(\) =>/);
  assert.doesNotMatch(script, /className = "principles-decay-stack"/);
  assert.doesNotMatch(script, /data-principles-decay-stack-card/);
  assert.doesNotMatch(script, /--stack-inset/);
  assert.doesNotMatch(script, /x:\s*"-28px"/);
  assert.doesNotMatch(script, /x:\s*"-38px"/);
  assert.doesNotMatch(script, /r:\s*"-14deg"/);
  assert.doesNotMatch(script, /runInit\("principles decay stacks", initPrinciplesDecayStacks\)/);
  assert.doesNotMatch(script, /const createStack = \(/);
  assert.doesNotMatch(script, /className = "stack-container"/);
  assert.doesNotMatch(script, /className = "card-rotate"/);
  assert.doesNotMatch(script, /refreshStackJitter/);
  assert.doesNotMatch(script, /startStackJitter/);
  assert.doesNotMatch(script, /stopStackJitter/);
  assert.doesNotMatch(script, /content\.querySelector\("\.principles-photo-overlay"\)\?\.remove\(\);/);
  assert.doesNotMatch(script, /initPrinciplesTiltedCards/);
  assert.doesNotMatch(script, /data-principles-tilted-card/);
  assert.match(css, /\.cursor-follower\s*{[^}]*position:\s*fixed;[^}]*width:\s*18px;[^}]*height:\s*18px;[^}]*background:\s*#8239ff;[^}]*pointer-events:\s*none;[^}]*will-change:\s*transform, opacity;/s);
  assert.match(css, /\.cursor-follower\s*{[^}]*box-shadow:\s*none;/s);
  assert.match(css, /\.cursor-follower\.is-visible\s*{[^}]*opacity:\s*0\.92;/s);
  assert.match(css, /@media \(pointer: coarse\), \(prefers-reduced-motion: reduce\)\s*{[^}]*\.cursor-follower\s*{[^}]*display:\s*none;/s);
  assert.match(script, /const initCursorFollower = \(\) =>/);
  assert.match(script, /querySelector\("\[data-cursor-follower\]"\)/);
  assert.match(script, /matchMedia\("\(pointer: coarse\)"\)/);
  assert.match(script, /matchMedia\("\(prefers-reduced-motion: reduce\)"\)/);
  assert.match(script, /const followerOffset = \{ x: 14, y: 18 \};/);
  assert.match(script, /window\.addEventListener\("pointermove", handlePointerMove, \{ passive: true \}\)/);
  assert.match(script, /translate3d\(\$\{current\.x \+ followerOffset\.x\}px, \$\{current\.y \+ followerOffset\.y\}px, 0\)/);
  assert.match(script, /requestAnimationFrame\(render\)/);
  assert.match(script, /runInit\("cursor follower", initCursorFollower\)/);
  assert.doesNotMatch(script, /const initPixelTrail = \(\) =>/);
  assert.doesNotMatch(script, /querySelector\("\[data-pixel-trail\]"\)/);
  assert.doesNotMatch(script, /const initDecayCard = \(\) =>/);
  assert.doesNotMatch(script, /querySelector\("\[data-decay-card\]"\)/);
  assert.doesNotMatch(script, /querySelectorAll\("\[data-card-stack\]"\)/);
  assert.match(script, /const scrollToHashTarget = \(hash = window\.location\.hash, behavior = "smooth"\) =>/);
  assert.match(script, /window\.scrollTo\(\{ top, behavior \}\)/);
  assert.match(script, /target\.id === "direction"/);
  assert.match(script, /top \+= window\.innerHeight/);
  assert.match(script, /const initDirectionReveal = \(\) =>/);
  assert.match(script, /querySelector\("#direction"\)/);
  assert.match(script, /is-direction-reveal-active/);
  assert.match(script, /is-direction-reveal-after/);
  assert.match(script, /runInit\("direction reveal", initDirectionReveal\)/);
  assert.doesNotMatch(script, /scrollToHashTarget\(window\.location\.hash, "auto"\)/);
  assert.match(script, /document\.querySelectorAll\('a\[href\^="#"\]'\)/);
  assert.doesNotMatch(script, /history\.pushState\(null, "", hash\)/);
  assert.match(script, /history\.replaceState\(null, "", window\.location\.pathname \+ window\.location\.search\)/);
  assert.match(script, /window\.requestAnimationFrame\(\(\) => scrollToHashTarget\(hash\)\)/);
  assert.match(script, /runInit\("anchor scroll", initAnchorScroll\)/);
  assert.match(script, /const initHeroVisibility = \(\) =>/);
  assert.match(script, /document\.body\.classList\.toggle\("is-past-hero"/);
  assert.match(script, /runInit\("hero visibility", initHeroVisibility\)/);
  assert.doesNotMatch(script, /initDirectionCoverPin/);
  assert.doesNotMatch(script, /direction-scroll-content/);
  assert.doesNotMatch(script, /--direction-pin-height/);
  assert.doesNotMatch(script, /direction\.style\.position = "fixed"/);
  assert.doesNotMatch(script, /runInit\("direction cover pin"/);
  assert.match(script, /target\.classList\.contains\("hero-page"\) && heroPin/);
  assert.match(script, /top = heroPin\.offsetTop/);
  assert.match(script, /const initWechatModal = \(\) =>/);
  assert.match(script, /querySelector\("\[data-wechat-modal\]"\)/);
  assert.match(script, /querySelector\("\[data-wechat-modal-open\]"\)/);
  assert.match(script, /modal\.hidden = false/);
  assert.match(script, /modal\.hidden = true/);
  assert.match(script, /event\.key === "Escape"/);
  assert.match(script, /runInit\("wechat modal", initWechatModal\)/);
  assert.match(script, /const initDecryptedText = \(\) =>/);
  assert.match(script, /querySelectorAll\("\[data-decrypted-text\]"\)/);
  assert.match(script, /new IntersectionObserver/);
  assert.match(script, /runInit\("decrypted text", initDecryptedText\)/);
  assert.doesNotMatch(script, /initComputerEnterTransition/);
  assert.match(script, /syncPageScrollPosition\(top\)/);

  const computerScript = fs.readFileSync(path.join(root, "hero-computer.js"), "utf8");
  assert.match(computerScript, /from "https:\/\/cdn\.jsdelivr\.net\/npm\/three@/);
  assert.match(computerScript, /GLTFLoader/);
  assert.doesNotMatch(computerScript, /EffectComposer/);
  assert.doesNotMatch(computerScript, /RGBShiftShader/);
  assert.match(computerScript, /const LEGACY_MODEL_URL = "assets\/computers\/scene\.gltf";/);
  assert.match(computerScript, /const MODEL_URL = "assets\/computers-candidate\/source\/computers\.glb";/);
  assert.match(computerScript, /monitor02_reference\.smd/);
  assert.match(computerScript, /monitor02_reference\.smd_2/);
  assert.match(computerScript, /monitor02_referencesmd/);
  assert.match(computerScript, /COMPUTER_NODE_CANDIDATES/);
  assert.match(computerScript, /sceneRoot\.getObjectByName\(nodeName\)/);
  assert.match(computerScript, /Box3/);
  assert.match(computerScript, /querySelector\("\[data-hero-computer\]"\)/);
  assert.match(computerScript, /VideoTexture/);
  assert.match(computerScript, /videoElement\.crossOrigin = "anonymous";/);
  assert.match(computerScript, /const useVideo = Boolean\(videoPath\);/);
  assert.match(computerScript, /CanvasTexture/);
  assert.match(computerScript, /const screenYaw = THREE\.MathUtils\.degToRad\(10\);/);
  assert.match(computerScript, /const screenPitch = THREE\.MathUtils\.degToRad\(10\);/);
  assert.match(computerScript, /const baseRotation = \{ x: -screenPitch, y: -Math\.PI \/ 2 \+ screenYaw, z: 0\.004 \};/);
  assert.match(computerScript, /renderer\.setPixelRatio\(Math\.min\(window\.devicePixelRatio \|\| 1, 1\.6\)\)/);
  assert.doesNotMatch(computerScript, /renderer\.toneMapping = THREE\.ACESFilmicToneMapping;/);
  assert.doesNotMatch(computerScript, /rgbShiftPass/);
  assert.match(computerScript, /renderer\.render\(scene, camera\)/);
  assert.match(computerScript, /new THREE\.HemisphereLight\(0xeef8ff, 0xd8cfaa, 1\.35\)/);
  assert.doesNotMatch(computerScript, /COMPUTER_SHELL_TINT/);
  assert.doesNotMatch(computerScript, /COMPUTER_SHELL_EMISSIVE/);
  assert.doesNotMatch(computerScript, /styleComputerShellMaterial/);
  assert.doesNotMatch(computerScript, /applyComputerShellStyle/);
  assert.doesNotMatch(computerScript, /computerStyle/);
  assert.doesNotMatch(computerScript, /COMPUTER_GHOST_LAYERS/);
  assert.doesNotMatch(computerScript, /addComputerGhostLayers/);
  assert.doesNotMatch(computerScript, /createComputerGhostLayer/);
  assert.doesNotMatch(computerScript, /computerGhostLayers/);
  assert.doesNotMatch(computerScript, /AdditiveBlending/);
  assert.doesNotMatch(computerScript, /Math\.PI \+ 0\.02/);
  assert.match(computerScript, /targetRotation/);
  assert.match(computerScript, /window\.addEventListener\("pointermove", handlePointerMove, \{ passive: true \}\)/);
  assert.match(computerScript, /const heroPin = container\.closest\("\.hero-pin"\) \|\| document\.querySelector\("\.hero-pin"\);/);
  assert.match(computerScript, /const shouldRunHeroComputer = \(\) =>/);
  assert.match(computerScript, /heroPin\.offsetHeight - window\.innerHeight/);
  assert.match(computerScript, /const setHeroComputerActive = \(nextActive\) =>/);
  assert.match(computerScript, /videoElement\.pause\(\);/);
  assert.match(computerScript, /videoElement\.play\(\)\.catch\(\(\) => \{\}\);/);
  assert.match(computerScript, /window\.cancelAnimationFrame\(renderFrameId\);/);
  assert.match(script, /const arrow = stage\.querySelector\("\[data-project-spiral-arrow\]"\)/);
  assert.match(script, /const triggerArrowPush = \(\) => \{/);
  assert.match(script, /arrow\.classList\.add\("is-pushing"\)/);
  assert.match(script, /stage\.classList\.add\("is-pushing"\)/);
  assert.match(script, /const applyProgressStep = \(direction\) => \{/);
  assert.match(script, /let completedSteps = 0;/);
  assert.match(script, /const visibleHistoryDepth = Math\.min\(renderRadius, completedSteps\);/);
  assert.match(script, /const firstIndex = center - visibleHistoryDepth;/);
  assert.match(script, /completedSteps = Math\.min\(renderRadius, completedSteps \+ Math\.abs\(direction\)\);/);
  assert.match(script, /completedSteps = 0;/);
  assert.match(script, /await triggerArrowPush\(\);[\s\S]*applyProgressStep\(direction\);/);
  assert.match(script, /window\.setTimeout\(async \(\) => \{/);
  assert.doesNotMatch(script, /window\.setInterval\(\(\) => stepProgress\(1\), autoDelay\)/);
  assert.match(script, /!hasStarted && offset < -0\.08/);
  assert.match(script, /const startLine = window\.innerHeight \* 0\.56/);
  assert.match(script, /setStarted\(rect\.top <= startLine && rect\.bottom > 0\)/);
  assert.match(script, /setActive\(entry\.isIntersecting\)/);
  assert.match(script, /item\.classList\.toggle\("is-current", Math\.abs\(offset\) < 0\.25\)/);
  assert.match(script, /stage\.classList\.toggle\("is-active", isActive\)/);
  assert.match(computerScript, /const scheduleRenderLoop = \(\) =>/);
  assert.match(computerScript, /container\.dataset\.heroComputerPaused = "true";/);
  assert.match(computerScript, /window\.addEventListener\("scroll", updateHeroComputerActivity, \{ passive: true \}\)/);
  assert.doesNotMatch(computerScript, /window\.setTimeout\(\(\) => requestAnimationFrame\(animate\), 250\)/);
  assert.match(computerScript, /THREE\.MathUtils\.lerp/);
  assert.match(computerScript, /modelRoot\.position\.set\(0\.02, -0\.1, 0\)/);
  assert.match(computerScript, /const DEBUG_QUERY = new URLSearchParams\(window\.location\.search\);/);
  assert.match(computerScript, /const DEBUG_SCREEN_ALIGNMENT = DEBUG_QUERY\.has\("screen-debug"\);/);
  assert.match(computerScript, /const SHOULD_PROBE_PIXELS = DEBUG_SCREEN_ALIGNMENT \|\| DEBUG_QUERY\.has\("screen-probe"\);/);
  assert.match(computerScript, /const SCREEN_PLANE_OFFSET = 0\.1;/);
  assert.match(computerScript, /const SCREEN_VIDEO_SCALE = 1\.1;/);
  assert.match(computerScript, /const MANUAL_SCREEN_CORNERS = \{/);
  assert.match(computerScript, /topLeft:\s*\[0\.217,\s*0\.418,\s*-0\.162\]/);
  assert.match(computerScript, /topRight:\s*\[0\.217,\s*0\.416,\s*0\.166\]/);
  assert.match(computerScript, /bottomLeft:\s*\[0\.217,\s*0\.157,\s*-0\.162\]/);
  assert.match(computerScript, /bottomRight:\s*\[0\.217,\s*0\.156,\s*0\.166\]/);
  assert.match(computerScript, /const SCREEN_SURFACE_SEGMENTS = \{ columns: 28, rows: 18 \};/);
  assert.match(computerScript, /const SCREEN_EDGE_CURVE = \{ top: 0\.014, right: 0\.009 \};/);
  assert.match(computerScript, /const SCREEN_FRAME_MASK_OVERSCAN = \{ horizontal: 0\.012, vertical: 0\.008 \};/);
  assert.doesNotMatch(computerScript, /SCREEN_GLASS_TRIM/);
  assert.doesNotMatch(computerScript, /SCREEN_VIDEO_INSET/);
  assert.doesNotMatch(computerScript, /SCREEN_RECESS_LIP_OFFSET/);
  assert.doesNotMatch(computerScript, /SCREEN_RECESS_BACKPLATE_OFFSET/);
  assert.doesNotMatch(computerScript, /SCREEN_FRAME_RIM_OFFSET/);
  assert.match(computerScript, /const SCREEN_CUT_PLANE_TOLERANCE = 0\.055;/);
  assert.match(computerScript, /function findScreenMesh\(sceneRoot\)/);
  assert.match(computerScript, /function createVideoTexture\(video\)/);
  assert.doesNotMatch(computerScript, /function applyVideoToScreenMesh\(screenMesh, texture\)/);
  assert.match(computerScript, /function createCurvedVideoSurface\(corners, texture\)/);
  assert.match(computerScript, /function getScreenBasis\(corners\)/);
  assert.doesNotMatch(computerScript, /function insetScreenCorners\(corners\)/);
  assert.match(computerScript, /function expandScreenCorners\(corners\)/);
  assert.match(computerScript, /function scaleScreenCorners\(corners, scale\)/);
  assert.doesNotMatch(computerScript, /function fitScreenCornersToGlass\(corners\)/);
  assert.doesNotMatch(computerScript, /function createScreenRecessLip\(corners\)/);
  assert.doesNotMatch(computerScript, /function createScreenFrameRim\(corners\)/);
  assert.doesNotMatch(computerScript, /function createScreenRecessBackplate\(corners\)/);
  assert.match(computerScript, /function isTriangleInsideScreenOpening\(centroid, basis\)/);
  assert.match(computerScript, /function cutScreenOpeningFromMesh\(mesh, corners\)/);
  assert.match(computerScript, /function cutNativeScreenOpening\(sceneRoot, corners\)/);
  assert.match(computerScript, /function applyStretchUV\(texture\)/);
  assert.doesNotMatch(computerScript, /applyCoverUV/);
  assert.doesNotMatch(computerScript, /videoAspect/);
  assert.match(computerScript, /function createScreenDebugHelpers\(corners, plane\)/);
  assert.match(computerScript, /function logMeshDiagnostics\(sceneRoot\)/);
  assert.match(computerScript, /console\.table\(diagnostics\)/);
  assert.match(computerScript, /new THREE\.BufferGeometry\(\)/);
  assert.match(computerScript, /geometry\.setAttribute\("position", new THREE\.Float32BufferAttribute\(positions, 3\)\)/);
  assert.match(computerScript, /geometry\.setAttribute\("uv", new THREE\.Float32BufferAttribute\(uvs, 2\)\)/);
  assert.doesNotMatch(computerScript, /new THREE\.PlaneGeometry\(width, height\)/);
  assert.match(computerScript, /new THREE\.MeshBasicMaterial/);
  assert.match(computerScript, /depthTest:\s*true/);
  assert.match(computerScript, /texture\.flipY = false/);
  assert.match(computerScript, /function orientVideoTextureForManualPlane\(texture\)/);
  assert.match(computerScript, /texture\.flipY = true;/);
  assert.match(computerScript, /container\.dataset\.videoFlipY = "true";/);
  assert.match(computerScript, /point\.addScaledVector\(normal, SCREEN_PLANE_OFFSET\)/);
  assert.doesNotMatch(computerScript, /const SCREEN_PLANE_OFFSET = -0\.035;/);
  assert.doesNotMatch(computerScript, /const SCREEN_PLANE_OFFSET = -0\.012;/);
  assert.doesNotMatch(computerScript, /const SCREEN_PLANE_OFFSET = 0\.004;/);
  assert.doesNotMatch(computerScript, /const SCREEN_PLANE_OFFSET = -0\.024;/);
  assert.doesNotMatch(computerScript, /const SCREEN_PLANE_OFFSET = -0\.08;/);
  assert.doesNotMatch(computerScript, /const SCREEN_PLANE_OFFSET = -0\.14;/);
  assert.doesNotMatch(computerScript, /const SCREEN_PLANE_OFFSET = 0\.08;/);
  assert.doesNotMatch(computerScript, /const SCREEN_PLANE_OFFSET = 0\.2;/);
  assert.doesNotMatch(computerScript, /const SCREEN_PLANE_OFFSET = 0\.4;/);
  assert.match(computerScript, /topBow = SCREEN_EDGE_CURVE\.top/);
  assert.match(computerScript, /rightBow = SCREEN_EDGE_CURVE\.right/);
  assert.match(computerScript, /point\.addScaledVector\(yAxis,\s*topBow \* topCurve\)/);
  assert.match(computerScript, /point\.addScaledVector\(xAxis,\s*rightBow \* rightCurve\)/);
  assert.doesNotMatch(computerScript, /point\.addScaledVector\(yAxis,\s*-topBow \* topCurve\)/);
  assert.doesNotMatch(computerScript, /point\.addScaledVector\(xAxis,\s*-rightBow \* rightCurve\)/);
  assert.match(computerScript, /const expandedCorners = expandScreenCorners\(corners\);/);
  assert.match(computerScript, /const scaledCorners = scaleScreenCorners\(expandedCorners, SCREEN_VIDEO_SCALE\);/);
  assert.match(computerScript, /texture\.repeat\.set/);
  assert.match(computerScript, /texture\.offset\.set/);
  assert.match(computerScript, /container\.dataset\.videoFit = "stretch";/);
  assert.match(computerScript, /container\.dataset\.screenCurveDirection = "outward";/);
  assert.match(computerScript, /container\.dataset\.screenPlaneOffset = String\(SCREEN_PLANE_OFFSET\);/);
  assert.match(computerScript, /container\.dataset\.screenVideoScale = String\(SCREEN_VIDEO_SCALE\);/);
  assert.match(computerScript, /container\.dataset\.screenFrameMaskOverscan = JSON\.stringify\(SCREEN_FRAME_MASK_OVERSCAN\);/);
  assert.doesNotMatch(computerScript, /screenGlassTrim/);
  assert.doesNotMatch(computerScript, /screenInset/);
  assert.doesNotMatch(computerScript, /screenRecessBackplate/);
  assert.doesNotMatch(computerScript, /black-well/);
  assert.doesNotMatch(computerScript, /screenRecessLip/);
  assert.doesNotMatch(computerScript, /screenFrameRim/);
  assert.doesNotMatch(computerScript, /color: 0xb7b89a/);
  assert.doesNotMatch(computerScript, /color: 0x050605/);
  assert.match(computerScript, /container\.dataset\.screenMask = "model-frame";/);
  assert.match(computerScript, /container\.dataset\.screenDepthPlacement = "behind-cut-screen";/);
  assert.match(computerScript, /container\.dataset\.nativeScreenCut = `\$\{screenCut\.removedTriangles\}\/\$\{screenCut\.totalTriangles\}`;/);
  assert.match(computerScript, /container\.dataset\.screenMesh = "manual-corners";/);
  assert.match(computerScript, /const screenCut = cutNativeScreenOpening\(model, MANUAL_SCREEN_CORNERS\);/);
  assert.match(computerScript, /const screenCut = cutNativeScreenOpening\(model, MANUAL_SCREEN_CORNERS\);[\s\S]*const screenTextureSource = screenTexture;/);
  assert.match(computerScript, /container\.dataset\.screenPlacementStrategy = "cut-native-screen";/);
  assert.doesNotMatch(computerScript, /if \(screenMesh && videoTexture\)/);
  assert.doesNotMatch(computerScript, /applyVideoToScreenMesh\(screenMesh, videoTexture\)/);
  assert.match(computerScript, /model\.add\(screen\)/);
  assert.doesNotMatch(computerScript, /model\.add\(screenRecessBackplate\)/);
  assert.doesNotMatch(computerScript, /model\.add\(screenRecessLip\)/);
  assert.doesNotMatch(computerScript, /model\.add\(screenFrameRim\)/);
  assert.match(computerScript, /if \(rect\.width < 32 \|\| rect\.height < 32\) return;/);
  assert.match(computerScript, /window\.resizeHeroComputer = resize;/);
  assert.doesNotMatch(computerScript, /function updateFlightCameraFromScreen\(screenTarget\)/);
  assert.doesNotMatch(computerScript, /screenTarget\.getWorldPosition\(screenCenter\)/);
  assert.doesNotMatch(computerScript, /flightCamera/);
  assert.doesNotMatch(computerScript, /container\.dataset\.flightCamera/);
  assert.doesNotMatch(computerScript, /window\.setHeroComputerFlightProgress/);
  assert.doesNotMatch(computerScript, /flightTarget/);
  assert.doesNotMatch(computerScript, /getHeroComputerScreenCenter/);
  assert.doesNotMatch(computerScript, /screen\.scale\.setScalar\(modelScale\)/);
  assert.doesNotMatch(computerScript, /new THREE\.ShaderMaterial/);
  assert.doesNotMatch(computerScript, /screen\.rotation\.y = Math\.PI \/ 2/);
  assert.match(computerScript, /const modelScale = 1\.826 \/ Math\.max\(size\.y, 0\.001\);/);
  assert.match(computerScript, /model\.position\.y -= 0\.02;/);
  assert.match(computerScript, /readPixels/);
  assert.match(computerScript, /pixelProbe/);
  assert.match(computerScript, /if \(SHOULD_PROBE_PIXELS && \(frame === 14 \|\| frame === 42\)\) probePixels\(\);/);
  assert.doesNotMatch(computerScript, /new THREE\.BoxGeometry/);
  assert.ok(fs.existsSync(path.join(root, "assets/computers/scene.gltf")));
  assert.ok(fs.existsSync(path.join(root, "assets/computers/scene.bin")));
  assert.ok(fs.existsSync(path.join(root, "assets/computers/textures/Monitor02_baseColor.png")));
  assert.ok(fs.existsSync(path.join(root, "assets/computers-candidate/source/computers.glb")));
  assert.ok(fs.existsSync(path.join(root, "assets/computers-candidate/textures/monitor02_1.png")));
  assert.ok(fs.existsSync(path.join(root, "assets/hero-screen.mp4")));
  assert.ok(fs.existsSync(path.join(root, "assets/projects/ascii-portrait.png")));
  assert.ok(!fs.existsSync(path.join(root, "project-ascii-art.js")));
  assert.equal(fs.readFileSync(path.join(root, "assets/projects/ascii-portrait.png"))[25], 6);

  assert.doesNotMatch(html, /circular-gallery\.js/);
  assert.doesNotMatch(html, /text-sphere\.js/);
  assert.doesNotMatch(script, /const sensitivity = 180;/);
  assert.doesNotMatch(script, /stack\.prepend\(card\)/);
  assert.doesNotMatch(script, /rotateX\(\$\{rotateX\}deg\) rotateY\(\$\{rotateY\}deg\)/);
  assert.doesNotMatch(script, /initQuoteStack\(\)/);
  assert.match(script, /className = "word"/);
});
